[bumpver]
current_version = "2022.1.0"
version_pattern = "YYYY.MM.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[bumpver.file_patterns]
"README.md" = [
    "{version}",
]
"bumpver.toml" = [
    'current_version = "{version}"',
]
"include/main.h" = ['__VERSION__ = "{version}"']
